spring:
  application:
    name: liquibase-postgres
  liquibase:
    enabled: true
    drop-first: true
    change-log: db/changelog/changelog.sql
  datasource:
    url: jdbc:h2:mem:config
    username: sa
    password: password
    driver-class-name: org.h2.Driver
